<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $table = 'teachers';

    protected $fillable = [
        'main_code',
        'area',
        'region_seq',
        'team_code',
        'attend_key',
        'teach_id',
        'teach_name',
        'teach_pw',
        'teach_email',
        'rrn',
        'team_name',
        'teach_phone',
        'teach_phone2',
        'remark',
        'teach_type',
        'group_seq',
        'join_date',
        'updated_at',
        'created_at',
        'created_id',
        'updated_id',
        'teach_gender',
        'profile_img_path',
        'resignation_date',
        'push_key',
        'device_type',
        'teach_attend',
        'teach_attend_end',
        'teach_pay',
        'teach_status',
        'auto_sms_push_key',
        'is_add_sms',
        'picture_pick',
        'teach_status_str',
        'pay_result_push',
        'is_use',
        'teach_address',
        'message_intro',
        'is_first_login',
        'is_auth_phone',
        'is_auth_email'
    ];

    protected $casts = [
        'id' => 'integer',
        'main_code' => 'string',
        'area' => 'string',
        'region_seq' => 'integer',
        'team_code' => 'string',
        'attend_key' => 'string',
        'teach_id' => 'string',
        'teach_name' => 'string',
        'teach_pw' => 'string',
        'teach_email' => 'string',
        'rrn' => 'string',
        'team_name' => 'string',
        'teach_phone' => 'string',
        'teach_phone2' => 'string',
        'remark' => 'string',
        'teach_type' => 'string',
        'group_seq' => 'integer',
        'join_date' => 'datetime',
        'updated_at' => 'datetime',
        'created_at' => 'datetime',
        'created_id' => 'string',
        'updated_id' => 'string',
        'teach_gender' => 'string',
        'profile_img_path' => 'string',
        'resignation_date' => 'datetime',
        'push_key' => 'string',
        'device_type' => 'string',
        // 'teach_attend' => 'time',
        // 'teach_attend_end' => 'time',
        'teach_pay' => 'string',
        'teach_status' => 'string',
        'auto_sms_push_key' => 'string',
        'is_add_sms' => 'string',
        'picture_pick' => 'integer',
        'teach_status_str' => 'string',
        'pay_result_push' => 'string',
        'is_use' => 'string',
        'teach_address' => 'string',
        'message_intro' => 'string',
        'is_first_login' => 'string',
        'is_auth_phone' => 'string',
        'is_auth_email' => 'string'
    ];
}
